### ISSUE TITLE
Exception on Startup

### ISSUE THREAD

**Issue by fullben** [microstream-one/bookstore-demo#5]
I tried to get this project running on my local machine (Windows 10, IntelliJ IDEA 2021.2 Community). Running the `VaadinApplication` class always fails with a `PersistenceException`:

```java
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getBookStoreDemo' defined in class path resource [one/microstream/demo/bookstore/VaadinApplicationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [one.microstream.demo.bookstore.BookStoreDemo]: Factory method 'getBookStoreDemo' threw exception; nested exception is one.microstream.persistence.exceptions.PersistenceException: Missing runtime type for required type handler for type: one.microstream.demo.bookstore.data.Data$Default
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [one.microstream.demo.bookstore.BookStoreDemo]: Factory method 'getBookStoreDemo' threw exception; nested exception is one.microstream.persistence.exceptions.PersistenceException: Missing runtime type for required type handler for type: one.microstream.demo.bookstore.data.Data$Default
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 32 common frames omitted
Caused by: one.microstream.persistence.exceptions.PersistenceException: Missing runtime type for required type handler for type: one.microstream.demo.bookstore.data.Data$Default
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.validateExistingType(PersistenceTypeHandlerManager.java:384) ~[microstream-persistence-06.00.00-MS-GA.jar:na]
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:434) ~[microstream-persistence-06.00.00-MS-GA.jar:na]
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.lambda$2(PersistenceTypeHandlerManager.java:479) ~[microstream-persistence-06.00.00-MS-GA.jar:na]
	at one.microstream.collections.ChainStorageStrong.iterate(ChainStorageStrong.java:1335) ~[microstream-base-06.00.00-MS-GA.jar:na]
	at one.microstream.collections.HashEnum.iterate(HashEnum.java:701) ~[microstream-base-06.00.00-MS-GA.jar:na]
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandlers(PersistenceTypeHandlerManager.java:478) ~[microstream-persistence-06.00.00-MS-GA.jar:na]
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandlersByTypeIds(PersistenceTypeHandlerManager.java:469) ~[microstream-persistence-06.00.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageManager$Default.ensureRequiredTypeHandlers(EmbeddedStorageManager.java:335) ~[microstream-storage-embedded-06.00.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:247) ~[microstream-storage-embedded-06.00.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1) ~[microstream-storage-embedded-06.00.00-MS-GA.jar:na]
	at one.microstream.demo.bookstore.BookStoreDemo.createStorageManager(BookStoreDemo.java:172) ~[classes/:na]
	at one.microstream.demo.bookstore.BookStoreDemo.storageManager(BookStoreDemo.java:148) ~[classes/:na]
	at one.microstream.demo.bookstore.VaadinApplicationConfiguration.getBookStoreDemo(VaadinApplicationConfiguration.java:23) ~[classes/:na]
	at one.microstream.demo.bookstore.VaadinApplicationConfiguration$$EnhancerBySpringCGLIB$$a062cf22.CGLIB$getBookStoreDemo$0(<generated>) ~[classes/:na]
	at one.microstream.demo.bookstore.VaadinApplicationConfiguration$$EnhancerBySpringCGLIB$$a062cf22$$FastClassBySpringCGLIB$$dbe0fbff.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at one.microstream.demo.bookstore.VaadinApplicationConfiguration$$EnhancerBySpringCGLIB$$a062cf22.getBookStoreDemo(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 33 common frames omitted
```
I've also encountered this issue when trying to run https://github.com/microstream-one/bookstore-demo-performance

**Comment by hg-ms** [comment]
Did you do any modifications to the demo code after running it at least once? 

The Exception
```
Missing runtime type for required type handler for type: one.microstream.demo.bookstore.data.Data$Default
```
Indicates that no class can be found for the class “one.microstream.demo.bookstore.data.Data$Default” that had been persisted before.

As a first test you could delete any existing storage. By default it should be the “data” directory in the project folder.

**Comment by fh-ms** [comment]
Looks like you are trying to start a new version of the demo with an old storage. We did some refactorings which are not backwards compatible. Just delete the storage directory and start over.

**Comment by fullben** [comment]
You're absolutely right, silly mistake on my part :)
